<?php

return [

    'legacy_skip_columns' => [
        'FGC_Creator',
        'FGC_CreateDate',
        'FGC_LastModifier',
        'FGC_LastModifyDate',
        'FGC_Rowversion',
        'FGC_UpdateHelp',
        'GUID',
    ],

    'legacy_labels' => [
        'ID' => 'ID',
        'Year' => '연도',
        'CreatedDate' => '작성일',
        'TR_Name' => '코치명',
        'SK_Code' => 'SK 코드',
        'Account_Name' => '기관명',
        'Teacher' => '교사명',
        'TeacherId' => '교사 ID',
        'SupportDate' => '지원 날짜',
        'Status' => '상태',
        'CompletedDate' => '완료일',
        'ReportType' => '보고서 유형',
        'LVA_TYPE' => 'LVA 유형',
        'Unit1' => 'Unit 1',
        'Lesson1' => 'Lesson 1',
        'Unit2' => 'Unit 2',
        'Lesson2' => 'Lesson 2',
        'Other' => '기타',
        'Comments1' => 'Comments 1',
        'Comments2' => 'Comments 2',
        'Overall_Comments' => 'Overall Comments',
        'ChaSu' => '차수',
        'Haggi' => '학기',
        'MeetingDate' => '미팅 날짜',
        'MeetingTime' => '미팅 시간',
        'MeetingType' => '미팅 유형',
        'Career' => '경력',
        'Unit' => 'Unit',
        'Lesson' => 'Lesson',
        'ClassName' => '반 이름',
        'Age' => '연령',
        'ClassLength' => '수업 길이',
        'FileLength' => '영상 길이',
    ],

    'mochi_config_map' => [
        'teacher_demo_lesson_support_reports' => 'coach_teacher_demo_lesson',
        'teacher_lva_fr_support_reports' => 'coach_teacher_lva_fr',
        'teacher_lva_fb_support_reports' => 'coach_teacher_lva_fb',
        'teacher_ls_onsite_lva_support_reports' => 'coach_teacher_ls_onsite_lva',
        'teacher_littleseed_con_support_reports' => 'coach_teacher_littleseed_con',
        'teacher_onsite_support_reports' => 'coach_teacher_onsite',
        'teacher_pro_con_support_reports' => 'coach_teacher_pro_con',
        'teacher_open_class_support_reports' => 'coach_teacher_open_class',
        'teacher_unit21_plus_support_reports' => 'coach_teacher_unit21_plus',
        'teacher_unit31_plus_support_reports' => 'coach_teacher_unit31_plus',
    ],

    'mochi_field_labels' => [
        'coach_name' => '코치명',
        'institution_name' => '기관명',
        'teacher_name' => '교사명',
        'support_date' => '지원 날짜',
        'status' => '상태',
        'progress_unit' => '진행 Unit',
        'progress_lesson' => '진행 Lesson',
        'other_notes' => '기타',
        'comments_primary' => 'Comments 1',
        'comments_secondary' => 'Comments 2',
        'overall_comments' => 'Overall Comments',
        'observe_unit' => '관찰 Unit',
        'observe_lesson' => '관찰 Lesson',
        'observe_class' => '관찰 반',
        'observe_age' => '관찰 연령',
        'teacher_experience' => '교사 경력',
        'session_number' => '차수',
        'semester_label' => '학기',
        'interview_date' => '미팅 날짜',
        'interview_time' => '미팅 시간',
        'method' => '지원 방법',
        'video_length_minutes' => '영상 길이(분)',
        'sk_code' => 'SK 코드',
    ],

    'account_field_labels' => [
        'tr_name' => '담당자(Coach)',
        'support_type' => '지원방법',
        'target' => '참석자',
        'issue' => '기관이슈',
        'to_account' => 'TO Account',
        'to_depart' => 'TO Depart',
        'others' => '기타',
        'support_date' => '지원 날짜',
        'support_time' => '지원 시간',
        'status' => '상태',
        'created_date' => '작성일',
        'completed_date' => '완료일',
    ],

];
