<?php

return [
    'data_source' => env('STORE_DATA_SOURCE', 'ecount'),
    'sales_history_source' => env('STORE_SALES_HISTORY_SOURCE', 'ecount'),
    'timeout' => (int) env('STORE_API_TIMEOUT', 10),
    'gnuboard' => [
        'enabled' => filter_var(env('STORE_GNUBOARD_ENABLED', 'true'), FILTER_VALIDATE_BOOLEAN),
        'connection' => env('STORE_GNUBOARD_CONNECTION', 'mysql_grapeseed_goods'),
        'item_table' => env('STORE_GNUBOARD_ITEM_TABLE', 'g5_shop_item'),
        'category_table' => env('STORE_GNUBOARD_CATEGORY_TABLE', 'g5_shop_category'),
        'category_id_column' => env('STORE_GNUBOARD_CATEGORY_ID_COLUMN', 'ca_id'),
        'category_name_column' => env('STORE_GNUBOARD_CATEGORY_NAME_COLUMN', 'ca_name'),
        'product_code_column' => env('STORE_GNUBOARD_PRODUCT_CODE_COLUMN', 'it_model'),
        'fallback_product_code_column' => env('STORE_GNUBOARD_FALLBACK_PRODUCT_CODE_COLUMN', 'it_id'),
        'item_name_column' => env('STORE_GNUBOARD_ITEM_NAME_COLUMN', 'it_name'),
        'item_category_l1_column' => env('STORE_GNUBOARD_ITEM_CATEGORY_L1_COLUMN', 'ca_id'),
        'item_category_l2_column' => env('STORE_GNUBOARD_ITEM_CATEGORY_L2_COLUMN', 'ca_id2'),
        'item_category_l3_column' => env('STORE_GNUBOARD_ITEM_CATEGORY_L3_COLUMN', 'ca_id3'),
        'notify_quantity_column' => env('STORE_GNUBOARD_NOTIFY_QTY_COLUMN', 'it_noti_qty'),
        'stock_quantity_column' => env('STORE_GNUBOARD_STOCK_QTY_COLUMN', 'it_stock_qty'),
        'sales' => [
            'order_table' => env('STORE_GNUBOARD_ORDER_TABLE', 'g5_shop_order'),
            'cart_table' => env('STORE_GNUBOARD_CART_TABLE', 'g5_shop_cart'),
            'order_id_column' => env('STORE_GNUBOARD_ORDER_ID_COLUMN', 'od_id'),
            'order_datetime_column' => env('STORE_GNUBOARD_ORDER_DATETIME_COLUMN', 'od_time'),
            'order_status_column' => env('STORE_GNUBOARD_ORDER_STATUS_COLUMN', 'od_status'),
            'cart_product_id_column' => env('STORE_GNUBOARD_CART_PRODUCT_ID_COLUMN', 'it_id'),
            'cart_quantity_column' => env('STORE_GNUBOARD_CART_QTY_COLUMN', 'ct_qty'),
            'cart_name_column' => env('STORE_GNUBOARD_CART_NAME_COLUMN', 'it_name'),
            'cart_status_column' => env('STORE_GNUBOARD_CART_STATUS_COLUMN', 'ct_status'),
            'order_settle_case_column' => env('STORE_GNUBOARD_ORDER_SETTLE_CASE_COLUMN', 'od_settle_case'),
            'order_customer_name_column' => env('STORE_GNUBOARD_ORDER_CUSTOMER_NAME_COLUMN', 'od_name'),
            'excluded_order_statuses' => array_values(array_filter(array_map(
                static fn (string $status): string => trim($status),
                explode(',', (string) env('STORE_GNUBOARD_EXCLUDED_ORDER_STATUSES', '취소,주문취소'))
            ), static fn (string $status): bool => $status !== '')),
            'excluded_cart_statuses' => array_values(array_filter(array_map(
                static fn (string $status): string => trim($status),
                explode(',', (string) env('STORE_GNUBOARD_EXCLUDED_CART_STATUSES', '취소'))
            ), static fn (string $status): bool => $status !== '')),
            'lookback_days' => max(1, (int) env('STORE_GNUBOARD_SALES_LOOKBACK_DAYS', 180)),
            'max_histories_per_product' => max(1, (int) env('STORE_GNUBOARD_SALES_MAX_HISTORIES', 5)),
            'max_rows_per_query' => max(1, (int) env('STORE_GNUBOARD_SALES_MAX_ROWS_PER_QUERY', 5000)),
        ],
    ],
    'ecount' => [
        'base_url' => env('ECOUNT_API_BASE_URL'),
        'zone_lookup_base_url' => env('ECOUNT_ZONE_LOOKUP_BASE_URL', 'https://oapi.ecount.com'),
        'zone' => env('ECOUNT_ZONE'),
        'session_id' => env('ECOUNT_SESSION_ID'),
        'inventory_endpoint' => env('ECOUNT_API_INVENTORY_ENDPOINT', '/OAPI/V2/InventoryBalance/GetListInventoryBalanceStatus'),
        'product_basic_endpoint' => env('ECOUNT_API_PRODUCT_BASIC_ENDPOINT', '/OAPI/V2/InventoryBasic/GetBasicProductsList'),
        'product_basic_chunk_size' => max(1, (int) env('ECOUNT_PRODUCT_BASIC_CHUNK_SIZE', 20)),
        'fetch_product_names' => filter_var(env('ECOUNT_FETCH_PRODUCT_NAMES', 'true'), FILTER_VALIDATE_BOOLEAN),
        'movement_endpoint' => env('ECOUNT_API_MOVEMENT_ENDPOINT', ''),
        'sale_list_endpoint' => env('ECOUNT_API_SALE_LIST_ENDPOINT', ''),
        'sale_list_include_com_code' => filter_var(env('ECOUNT_SALE_LIST_INCLUDE_COM_CODE', 'true'), FILTER_VALIDATE_BOOLEAN),
        'fetch_deduct_logs' => filter_var(env('ECOUNT_FETCH_DEDUCT_LOGS', 'true'), FILTER_VALIDATE_BOOLEAN),
        'movement_chunk_size' => max(1, (int) env('ECOUNT_MOVEMENT_CHUNK_SIZE', 20)),
        'movement_lookback_days' => max(1, (int) env('ECOUNT_MOVEMENT_LOOKBACK_DAYS', 90)),
        'warehouse_code' => env('ECOUNT_WAREHOUSE_CODE'),
        'base_date' => env('ECOUNT_BASE_DATE'),
        'product_code' => env('ECOUNT_PRODUCT_CODE'),
        'inventory_max_prod_cd' => max(1, (int) env('ECOUNT_INVENTORY_MAX_PROD_CD', 20)),
        'cache_ttl_seconds' => max(0, (int) env('ECOUNT_CACHE_TTL_SECONDS', 120)),
        'cache_prefix' => env('ECOUNT_CACHE_PREFIX', 'store_inventory'),
        'session_refresh_enabled' => filter_var(env('ECOUNT_SESSION_REFRESH_ENABLED', 'false'), FILTER_VALIDATE_BOOLEAN),
        'auto_login_when_empty_session' => filter_var(env('ECOUNT_AUTO_LOGIN_WHEN_EMPTY_SESSION', 'true'), FILTER_VALIDATE_BOOLEAN),
        'zone_endpoint' => env('ECOUNT_API_ZONE_ENDPOINT', '/OAPI/V2/Zone'),
        'login_endpoint' => env('ECOUNT_API_LOGIN_ENDPOINT', '/OAPI/V2/OAPILogin'),
        'com_code' => env('ECOUNT_COM_CODE'),
        'user_id' => env('ECOUNT_USER_ID'),
        'api_cert_key' => env('ECOUNT_API_CERT_KEY'),
        'lan_type' => env('ECOUNT_LAN_TYPE', 'ko-KR'),
        'zero_flag' => env('ECOUNT_ZERO_FLAG', 'N'),
        'bal_flag' => env('ECOUNT_BAL_FLAG', 'N'),
        'del_gubun' => env('ECOUNT_DEL_GUBUN', 'N'),
        'safe_flag' => env('ECOUNT_SAFE_FLAG', 'N'),
    ],
];
